/* ─────────────────────────────────────────────────────────────
   src/utils/quizQuestions.js
   140 domande BLINDATE sulla S.S. Lazio.
   Tutti i fatti verificati da almeno 2 fonti tra:
   Wikipedia, sslazio.it, laziowiki.org, sslaziomuseum.com,
   transfermarkt, Lega Serie A, Sky Sport, Gazzetta, Corriere,
   Repubblica, ANSA, Il Messaggero.
   Difficoltà medio-alta. Indice 0 = risposta corretta.
   Su Claudio Lotito: SOLO fatti negativi documentati.
   ───────────────────────────────────────────────────────────── */

export const QUIZ_QUESTIONS = [
  {"id":1,"q":"In che anno fu fondata la Società Podistica Lazio?","options":["1900","1898","1905","1910"],"answer":0,"cat":"Storia"},
  {"id":2,"q":"In quale data esatta nacque la Lazio?","options":["9 gennaio 1900","1 novembre 1900","13 gennaio 1900","9 gennaio 1901"],"answer":0,"cat":"Storia"},
  {"id":3,"q":"Chi fu il principale fondatore della Lazio?","options":["Luigi Bigiarelli","Fortunato Ballerini","Sante Ancherani","Giuseppe Pedercini"],"answer":0,"cat":"Storia"},
  {"id":4,"q":"In quale piazza di Roma fu fondata la Lazio?","options":["Piazza della Libertà","Piazza del Popolo","Piazza d'Armi","Piazza di Siena"],"answer":0,"cat":"Storia"},
  {"id":5,"q":"A quale corpo militare apparteneva il fondatore Luigi Bigiarelli?","options":["Bersaglieri","Alpini","Carabinieri","Granatieri"],"answer":0,"cat":"Storia"},
  {"id":6,"q":"A quale bandiera si ispirano i colori biancocelesti della Lazio?","options":["Grecia","Argentina","Svezia","Uruguay"],"answer":0,"cat":"Storia"},
  {"id":7,"q":"Qual è l'animale simbolo della Lazio?","options":["L'aquila","Il leone","La lupa","Il falco"],"answer":0,"cat":"Storia"},
  {"id":8,"q":"In che anno venne istituita ufficialmente la sezione calcistica della Lazio?","options":["1910","1900","1901","1925"],"answer":0,"cat":"Storia"},
  {"id":9,"q":"La Lazio fu la prima società calcistica italiana a fare cosa nel 1998?","options":["Quotarsi in Borsa","Vincere la Coppa UEFA","Avere uno sponsor","Costruire un museo"],"answer":0,"cat":"Storia"},
  {"id":10,"q":"Quanti furono i 'padri fondatori' della Lazio nel 1900?","options":["Nove","Undici","Quindici","Sette"],"answer":0,"cat":"Storia"},
  {"id":11,"q":"Quale presidente, nel 1910, è legato all'istituzione ufficiale della sezione calcio?","options":["Fortunato Ballerini","Umberto Lenzini","Leonardo Siliato","Giorgio Vaccaro"],"answer":0,"cat":"Storia"},
  {"id":12,"q":"In quale data la Lazio vinse il suo primo scudetto?","options":["12 maggio 1974","14 maggio 2000","19 maggio 1999","24 settembre 1958"],"answer":0,"cat":"Scudetti"},
  {"id":13,"q":"Contro quale squadra la Lazio chiuse i conti per lo scudetto 1974?","options":["Foggia","Sampdoria","Juventus","Napoli"],"answer":0,"cat":"Scudetti"},
  {"id":14,"q":"Con quale punteggio la Lazio batté il Foggia il 12 maggio 1974?","options":["1-0","2-0","3-1","2-1"],"answer":0,"cat":"Scudetti"},
  {"id":15,"q":"Chi trasformò il rigore decisivo contro il Foggia nel 1974?","options":["Giorgio Chinaglia","Vincenzo D'Amico","Renzo Garlaschelli","Franco Nanni"],"answer":0,"cat":"Scudetti"},
  {"id":16,"q":"Chi era l'allenatore della Lazio campione d'Italia 1974?","options":["Tommaso Maestrelli","Juan Carlos Lorenzo","Roberto Lovati","Bob Lovati"],"answer":0,"cat":"Scudetti"},
  {"id":17,"q":"Quanti gol segnò Chinaglia da capocannoniere nel campionato 1973-74?","options":["24","21","19","27"],"answer":0,"cat":"Bomber"},
  {"id":18,"q":"Chi era il presidente della Lazio dello scudetto 1974?","options":["Umberto Lenzini","Sergio Cragnotti","Gianmarco Calleri","Claudio Lotito"],"answer":0,"cat":"Scudetti"},
  {"id":19,"q":"Chi era il capitano della Lazio scudettata nel 1974?","options":["Pino Wilson","Giorgio Chinaglia","Luciano Re Cecconi","Mario Frustalupi"],"answer":0,"cat":"Scudetti"},
  {"id":20,"q":"In quale data la Lazio conquistò il secondo scudetto?","options":["14 maggio 2000","12 maggio 1974","19 maggio 1999","6 maggio 2000"],"answer":0,"cat":"Scudetti"},
  {"id":21,"q":"Quale partita doveva finire perché la Lazio fosse campione nel 2000?","options":["Perugia-Juventus","Inter-Juventus","Perugia-Lazio","Reggina-Juventus"],"answer":0,"cat":"Scudetti"},
  {"id":22,"q":"Con quale risultato la Lazio batté la Reggina il 14 maggio 2000?","options":["3-0","2-0","3-1","1-0"],"answer":0,"cat":"Scudetti"},
  {"id":23,"q":"Chi segnò il gol del Perugia che 'consegnò' lo scudetto 2000 alla Lazio?","options":["Alessandro Calori","Marco Materazzi","Fabrizio Ravanelli","Massimiliano Allegri"],"answer":0,"cat":"Scudetti"},
  {"id":24,"q":"Quale arbitro diresse la celebre Perugia-Juventus del 14 maggio 2000?","options":["Pierluigi Collina","Massimo De Santis","Graziano Cesari","Stefano Braschi"],"answer":0,"cat":"Scudetti"},
  {"id":25,"q":"Perché la ripresa di Perugia-Juventus fu ritardata di circa 70 minuti?","options":["Un nubifragio allagò il campo","Un blackout","Un'invasione di campo","Nebbia fitta"],"answer":0,"cat":"Scudetti"},
  {"id":26,"q":"Chi era l'allenatore della Lazio campione d'Italia nel 2000?","options":["Sven-Göran Eriksson","Dino Zoff","Roberto Mancini","Alberto Zaccheroni"],"answer":0,"cat":"Scudetti"},
  {"id":27,"q":"Chi era il presidente della Lazio durante lo scudetto 2000?","options":["Sergio Cragnotti","Dino Zoff","Claudio Lotito","Umberto Lenzini"],"answer":0,"cat":"Scudetti"},
  {"id":28,"q":"Quanti punti di vantaggio aveva la Juventus a otto giornate dalla fine nel 2000?","options":["Nove","Cinque","Sette","Tre"],"answer":0,"cat":"Scudetti"},
  {"id":29,"q":"Chi segnò il primo gol (su rigore) di Lazio-Reggina nell'ultima giornata 2000?","options":["Simone Inzaghi","Juan Verón","Diego Simeone","Marcelo Salas"],"answer":0,"cat":"Scudetto 2000"},
  {"id":30,"q":"Quanti scudetti ha vinto la Lazio nella sua storia?","options":["2","3","1","4"],"answer":0,"cat":"Scudetti"},
  {"id":31,"q":"Quante Coppe Italia ha vinto la Lazio (al 2024)?","options":["7","6","5","8"],"answer":0,"cat":"Coppe Italia"},
  {"id":32,"q":"In che anno la Lazio vinse la sua prima Coppa Italia?","options":["1958","1974","1998","1969"],"answer":0,"cat":"Coppe Italia"},
  {"id":33,"q":"Contro quale squadra la Lazio vinse la Coppa Italia 1958?","options":["Fiorentina","Milan","Juventus","Inter"],"answer":0,"cat":"Coppe Italia"},
  {"id":34,"q":"Chi segnò il gol decisivo nella finale di Coppa Italia 1958?","options":["Maurilio Prini","Bob Lovati","Humberto Tozzi","Francesco Janich"],"answer":0,"cat":"Coppe Italia"},
  {"id":35,"q":"Chi era l'allenatore della Lazio nella Coppa Italia 1958?","options":["Fulvio Bernardini","Tommaso Maestrelli","Juan Carlos Lorenzo","Roberto Lovati"],"answer":0,"cat":"Coppe Italia"},
  {"id":36,"q":"La Coppa Italia 1958 fu per la Lazio:","options":["Il primo trofeo ufficiale della storia","Il secondo trofeo","Una rivincita europea","Un titolo regionale"],"answer":0,"cat":"Coppe Italia"},
  {"id":37,"q":"Contro chi vinse la Lazio la storica Coppa Italia del 26 maggio 2013?","options":["Roma","Juventus","Milan","Sampdoria"],"answer":0,"cat":"Coppe Italia"},
  {"id":38,"q":"Chi segnò il gol del derby di Coppa Italia 2013 vinto dalla Lazio?","options":["Senad Lulić","Antonio Candreva","Miroslav Klose","Hernanes"],"answer":0,"cat":"Coppe Italia"},
  {"id":39,"q":"Chi allenava la Lazio nella Coppa Italia 2012-13 vinta col derby?","options":["Vladimir Petković","Edy Reja","Stefano Pioli","Simone Inzaghi"],"answer":0,"cat":"Coppe Italia"},
  {"id":40,"q":"Contro quale squadra la Lazio vinse la Coppa Italia 2004?","options":["Juventus","Milan","Inter","Sampdoria"],"answer":0,"cat":"Coppe Italia"},
  {"id":41,"q":"Chi era l'allenatore della Lazio per la Coppa Italia 2004?","options":["Roberto Mancini","Delio Rossi","Sven-Göran Eriksson","Dino Zoff"],"answer":0,"cat":"Coppe Italia"},
  {"id":42,"q":"Contro quale squadra la Lazio vinse la Coppa Italia 2009?","options":["Sampdoria","Inter","Roma","Juventus"],"answer":0,"cat":"Coppe Italia"},
  {"id":43,"q":"Chi guidava la Lazio nella Coppa Italia 2009?","options":["Delio Rossi","Davide Ballardini","Edy Reja","Roberto Mancini"],"answer":0,"cat":"Allenatori"},
  {"id":44,"q":"Chi era l'allenatore della Lazio nella Coppa Italia 2019?","options":["Simone Inzaghi","Vladimir Petković","Stefano Pioli","Maurizio Sarri"],"answer":0,"cat":"Coppe Italia"},
  {"id":45,"q":"Quale trofeo europeo vinse la Lazio il 19 maggio 1999?","options":["Coppa delle Coppe","Coppa UEFA","Coppa dei Campioni","Coppa Intertoto"],"answer":0,"cat":"Europa"},
  {"id":46,"q":"In quale stadio la Lazio vinse la Coppa delle Coppe 1999?","options":["Villa Park di Birmingham","Wembley","Parco dei Principi","Stade Louis II"],"answer":0,"cat":"Europa"},
  {"id":47,"q":"Contro quale squadra la Lazio vinse la Coppa delle Coppe 1999?","options":["Maiorca","Chelsea","Lokomotiv Mosca","Partizan"],"answer":0,"cat":"Europa"},
  {"id":48,"q":"Con quale punteggio la Lazio batté il Maiorca nella finale del 1999?","options":["2-1","1-0","3-1","2-0"],"answer":0,"cat":"Europa"},
  {"id":49,"q":"Chi segnò il primo gol della Lazio nella finale di Birmingham 1999?","options":["Christian Vieri","Pavel Nedvěd","Marcelo Salas","Roberto Mancini"],"answer":0,"cat":"Europa"},
  {"id":50,"q":"Chi segnò il gol vittoria all'81' nella finale di Coppa delle Coppe 1999?","options":["Pavel Nedvěd","Christian Vieri","Siniša Mihajlović","Dejan Stanković"],"answer":0,"cat":"Europa"},
  {"id":51,"q":"Cosa rese storica la finale di Coppa delle Coppe 1999 oltre alla vittoria Lazio?","options":["Fu l'ultima edizione del torneo","Fu la prima edizione","Si giocò ai rigori","Durò due gare"],"answer":0,"cat":"Europa"},
  {"id":52,"q":"Quale squadra batté la Lazio nella Supercoppa UEFA 1999?","options":["Manchester United","Bayern Monaco","Real Madrid","Barcellona"],"answer":0,"cat":"Europa"},
  {"id":53,"q":"Chi segnò il gol-vittoria della Lazio nella Supercoppa UEFA 1999 a Monaco?","options":["Marcelo Salas","Christian Vieri","Pavel Nedvěd","Roberto Mancini"],"answer":0,"cat":"Europa"},
  {"id":54,"q":"In quale finale europea la Lazio fu sconfitta dall'Inter nel 1998?","options":["Coppa UEFA","Coppa delle Coppe","Champions League","Supercoppa UEFA"],"answer":0,"cat":"Europa"},
  {"id":55,"q":"Quale torneo internazionale (non UEFA) vinse la Lazio nel 1971?","options":["Coppa delle Alpi","Coppa Mitropa","Coppa Latina","Coppa Anglo-Italiana"],"answer":0,"cat":"Europa"},
  {"id":56,"q":"Chi è il miglior marcatore di sempre della Lazio?","options":["Ciro Immobile","Silvio Piola","Giorgio Chinaglia","Giuseppe Signori"],"answer":0,"cat":"Bomber"},
  {"id":57,"q":"Quante reti ufficiali ha segnato Immobile con la Lazio (record assoluto)?","options":["207","159","127","123"],"answer":0,"cat":"Bomber"},
  {"id":58,"q":"Chi è il secondo miglior marcatore di sempre della Lazio?","options":["Silvio Piola","Giuseppe Signori","Giorgio Chinaglia","Tommaso Rocchi"],"answer":0,"cat":"Bomber"},
  {"id":59,"q":"Quanti gol segnò Silvio Piola con la maglia della Lazio?","options":["159","207","127","123"],"answer":0,"cat":"Bomber"},
  {"id":60,"q":"Di quale primato della Serie A è detentore Silvio Piola?","options":["Miglior marcatore di sempre con 274 reti","Più presenze di sempre","Più rigori segnati","Più gol in una stagione"],"answer":0,"cat":"Bomber"},
  {"id":61,"q":"Quante reti realizzò Immobile nella stagione record 2019-20?","options":["36","29","27","31"],"answer":0,"cat":"Bomber"},
  {"id":62,"q":"Con il record di 36 gol del 2019-20 Immobile eguagliò quale giocatore?","options":["Gonzalo Higuaín","Cristiano Ronaldo","Luca Toni","Antonio Di Natale"],"answer":0,"cat":"Bomber"},
  {"id":63,"q":"Quale riconoscimento europeo vinse Immobile nella stagione 2019-20?","options":["Scarpa d'Oro","Pallone d'Oro","Scarpa d'Argento","Golden Boy"],"answer":0,"cat":"Bomber"},
  {"id":64,"q":"Chi è il miglior marcatore straniero di sempre della Lazio?","options":["Sergej Milinković-Savić","Pavel Nedvěd","Miroslav Klose","Hernán Crespo"],"answer":0,"cat":"Bomber"},
  {"id":65,"q":"Quante reti totali segnò Milinković-Savić con la Lazio?","options":["69","61","52","45"],"answer":0,"cat":"Moderni"},
  {"id":66,"q":"Quante volte Giuseppe Signori fu capocannoniere di Serie A con la Lazio?","options":["Tre","Due","Quattro","Una"],"answer":0,"cat":"Bomber"},
  {"id":67,"q":"In quali stagioni Signori vinse la classifica marcatori con la Lazio?","options":["1992-93, 1993-94, 1995-96","1990-91, 1992-93, 1994-95","1993-94, 1996-97, 1997-98","1991-92, 1994-95, 1996-97"],"answer":0,"cat":"Bomber"},
  {"id":68,"q":"Da quale club arrivò Giuseppe Signori alla Lazio nel 1992?","options":["Foggia","Bologna","Parma","Cagliari"],"answer":0,"cat":"Anni 70-90"},
  {"id":69,"q":"Quante reti totali segnò Signori con la maglia della Lazio?","options":["127","105","159","123"],"answer":0,"cat":"Bomber"},
  {"id":70,"q":"In quale tragica circostanza morì Luciano Re Cecconi nel 1977?","options":["Ucciso da un gioielliere durante uno scherzo","Incidente stradale","Malattia improvvisa","Incidente di gioco"],"answer":0,"cat":"Anni 70-90"},
  {"id":71,"q":"In quale data morì Luciano Re Cecconi?","options":["18 gennaio 1977","2 dicembre 1976","12 maggio 1974","28 ottobre 1979"],"answer":0,"cat":"Anni 70-90"},
  {"id":72,"q":"Quanti anni aveva Re Cecconi quando morì?","options":["28","25","31","34"],"answer":0,"cat":"Anni 70-90"},
  {"id":73,"q":"Quale soprannome avevano dato a Luciano Re Cecconi?","options":["Angelo biondo","Long John","Il Maestro","Cecco"],"answer":0,"cat":"Anni 70-90"},
  {"id":74,"q":"Di quale malattia si ammalò Tommaso Maestrelli?","options":["Linfoma/cancro","Infarto","Malaria","Diabete"],"answer":0,"cat":"Allenatori"},
  {"id":75,"q":"In quale anno morì Tommaso Maestrelli?","options":["1976","1977","1974","1979"],"answer":0,"cat":"Allenatori"},
  {"id":76,"q":"Dove nacque il capitano Pino Wilson?","options":["Darlington, Inghilterra","Napoli","Roma","Cardiff, Galles"],"answer":0,"cat":"Anni 70-90"},
  {"id":77,"q":"In che ruolo giocava Pino Wilson nella Lazio del 1974?","options":["Libero/difensore","Centravanti","Ala","Portiere"],"answer":0,"cat":"Anni 70-90"},
  {"id":78,"q":"Dove crebbe calcisticamente Giorgio Chinaglia da ragazzo?","options":["In Galles (Cardiff/Swansea)","In Argentina","A Napoli","A Roma"],"answer":0,"cat":"Anni 70-90"},
  {"id":79,"q":"In quale città toscana nacque Giorgio Chinaglia?","options":["Carrara","Pisa","Livorno","Lucca"],"answer":0,"cat":"Anni 70-90"},
  {"id":80,"q":"In quale club americano si trasferì Chinaglia nel 1976?","options":["New York Cosmos","Los Angeles Aztecs","Tampa Bay Rowdies","Chicago Sting"],"answer":0,"cat":"Anni 70-90"},
  {"id":81,"q":"Chi era il regista/'centro motore' della Lazio scudetto 1974?","options":["Mario Frustalupi","Vincenzo D'Amico","Franco Nanni","Giancarlo Oddi"],"answer":0,"cat":"Anni 70-90"},
  {"id":82,"q":"Quale giovane talento del vivaio si affermò nella Lazio del 1974?","options":["Vincenzo D'Amico","Bruno Giordano","Lionello Manfredonia","Tommaso Rocchi"],"answer":0,"cat":"Anni 70-90"},
  {"id":83,"q":"Chi era il portiere titolare della Lazio campione nel 1974?","options":["Felice Pulici","Bob Lovati","Luca Marchegiani","Fernando Orsi"],"answer":0,"cat":"Anni 70-90"},
  {"id":84,"q":"In quale anno Bruno Giordano fu capocannoniere della Serie A con la Lazio?","options":["1978-79","1973-74","1983-84","1985-86"],"answer":0,"cat":"Anni 70-90"},
  {"id":85,"q":"Chi era il difensore centrale, capitano e simbolo della Lazio del 2000?","options":["Alessandro Nesta","Giuseppe Favalli","Paolo Negro","Fernando Couto"],"answer":0,"cat":"Scudetto 2000"},
  {"id":86,"q":"Quale centrocampista ceco della Lazio 2000 vinse poi il Pallone d'Oro (2003)?","options":["Pavel Nedvěd","Dejan Stanković","Juan Verón","Matías Almeyda"],"answer":0,"cat":"Scudetto 2000"},
  {"id":87,"q":"Quale attaccante cileno faceva parte della Lazio scudetto 2000?","options":["Marcelo Salas","Iván Zamorano","Hernán Crespo","Claudio López"],"answer":0,"cat":"Scudetto 2000"},
  {"id":88,"q":"Quale 'Cholo' argentino fu decisivo nello scudetto Lazio 2000?","options":["Diego Simeone","Matías Almeyda","Juan Verón","Hernán Crespo"],"answer":0,"cat":"Scudetto 2000"},
  {"id":89,"q":"Da quale club arrivò Simone Inzaghi alla Lazio prima dello scudetto 2000?","options":["Piacenza","Atalanta","Parma","Brescia"],"answer":0,"cat":"Scudetto 2000"},
  {"id":90,"q":"Quale serbo della Lazio 2000 era specialista delle punizioni?","options":["Siniša Mihajlović","Dejan Stanković","Sergej Milinković","Darko Kovačević"],"answer":0,"cat":"Scudetto 2000"},
  {"id":91,"q":"Per quale cifra record la Lazio acquistò Hernán Crespo nel 2000?","options":["110 miliardi di lire (€53,6 mln)","90 miliardi di lire","70 miliardi di lire","45 miliardi di lire"],"answer":0,"cat":"Mercato"},
  {"id":92,"q":"Da quale club arrivò Crespo alla Lazio?","options":["Parma","Valencia","Inter","Fiorentina"],"answer":0,"cat":"Mercato"},
  {"id":93,"q":"Quale giocatore rappresenta la cessione più remunerativa della storia Lazio (€48,3 mln)?","options":["Christian Vieri","Pavel Nedvěd","Juan Verón","Sergej Milinković-Savić"],"answer":0,"cat":"Mercato"},
  {"id":94,"q":"A quale club fu ceduto Christian Vieri nel 1999?","options":["Inter","Juventus","Milan","Atletico Madrid"],"answer":0,"cat":"Mercato"},
  {"id":95,"q":"A quale club fu venduto Milinković-Savić nel 2023?","options":["Al-Hilal","Al-Nassr","Al-Ittihad","Al-Duhail"],"answer":0,"cat":"Mercato"},
  {"id":96,"q":"Per quale cifra fissa la Lazio cedette Milinković all'Al-Hilal (2023)?","options":["40 milioni di euro","60 milioni di euro","25 milioni di euro","80 milioni di euro"],"answer":0,"cat":"Mercato"},
  {"id":97,"q":"Da quale club arrivò Luis Alberto alla Lazio nel 2016?","options":["Liverpool","Siviglia","Barcellona","Deportivo"],"answer":0,"cat":"Moderni"},
  {"id":98,"q":"Da quale club la Lazio acquistò Milinković-Savić nel 2015?","options":["Genk","Vojvodina","Fiorentina","Anderlecht"],"answer":0,"cat":"Moderni"},
  {"id":99,"q":"Da quale club arrivò Ciro Immobile alla Lazio nel 2016?","options":["Siviglia","Borussia Dortmund","Torino","Genoa"],"answer":0,"cat":"Moderni"},
  {"id":100,"q":"Quante reti totali segnò Miroslav Klose con la Lazio?","options":["64","69","52","45"],"answer":0,"cat":"Moderni"},
  {"id":101,"q":"Chi detiene il record di presenze ufficiali nella storia della Lazio?","options":["Stefan Radu","Senad Lulić","Giuseppe Favalli","Pino Wilson"],"answer":0,"cat":"Moderni"},
  {"id":102,"q":"Quante presenze ufficiali totalizzò Stefan Radu con la Lazio?","options":["427","371","341","318"],"answer":0,"cat":"Moderni"},
  {"id":103,"q":"Quale bosniaco è secondo per presenze straniere e segnò il gol-derby del 2013?","options":["Senad Lulić","Stefan Radu","Lucas Biglia","Dušan Basta"],"answer":0,"cat":"Moderni"},
  {"id":104,"q":"Chi è l'allenatore più vincente della storia della Lazio (7 trofei)?","options":["Sven-Göran Eriksson","Simone Inzaghi","Tommaso Maestrelli","Maurizio Sarri"],"answer":0,"cat":"Allenatori"},
  {"id":105,"q":"Chi detiene il record di partite ufficiali da allenatore della Lazio?","options":["Simone Inzaghi","Sven-Göran Eriksson","Guido Baccani","Edy Reja"],"answer":0,"cat":"Allenatori"},
  {"id":106,"q":"Quale allenatore guidò la Lazio per ben 18 anni (1906-1924)?","options":["Guido Baccani","Fulvio Bernardini","Roberto Lovati","Dezső Kőszegy"],"answer":0,"cat":"Allenatori"},
  {"id":107,"q":"Quale leggendario portiere fu allenatore della Lazio dal 1994 al 1997?","options":["Dino Zoff","Luca Marchegiani","Felice Pulici","Bob Lovati"],"answer":0,"cat":"Allenatori"},
  {"id":108,"q":"Quale tecnico arrivò alla Lazio e si dimise due giorni dopo la firma (2016)?","options":["Marcelo Bielsa","Vladimir Petković","Stefano Pioli","Edy Reja"],"answer":0,"cat":"Allenatori"},
  {"id":109,"q":"Chi sostituì Stefano Pioli sulla panchina della Lazio nel 2016?","options":["Simone Inzaghi","Vladimir Petković","Marcelo Bielsa","Edy Reja"],"answer":0,"cat":"Allenatori"},
  {"id":110,"q":"In quale anno Maurizio Sarri divenne allenatore della Lazio?","options":["2021","2019","2020","2022"],"answer":0,"cat":"Allenatori"},
  {"id":111,"q":"Quale primo stadio/campo usò la Lazio dal 1914?","options":["Rondinella","Flaminio","Olimpico","Stadio Nazionale"],"answer":0,"cat":"Stadio"},
  {"id":112,"q":"Cosa distrusse buona parte dello stadio della Rondinella nel 1957?","options":["Un incendio","Un bombardamento","Un terremoto","Un'alluvione"],"answer":0,"cat":"Stadio"},
  {"id":113,"q":"Quale stadio sorse sull'area del vecchio Stadio Nazionale per le Olimpiadi 1960?","options":["Stadio Flaminio","Stadio Olimpico","Stadio dei Marmi","Stadio Tor di Quinto"],"answer":0,"cat":"Stadio"},
  {"id":114,"q":"In quale stadio la Lazio gioca le partite casalinghe dagli anni '50?","options":["Stadio Olimpico","Stadio Flaminio","Rondinella","Stadio Nazionale"],"answer":0,"cat":"Stadio"},
  {"id":115,"q":"In quale stadio giocò la Lazio nel 1989-90 durante i lavori per Italia '90?","options":["Flaminio","Rondinella","Tor di Quinto","Testaccio"],"answer":0,"cat":"Stadio"},
  {"id":116,"q":"Chi vinse il primo derby della Capitale (8 dicembre 1929)?","options":["Roma","Lazio","Pareggio","Sospeso"],"answer":0,"cat":"Derby"},
  {"id":117,"q":"Chi è il miglior marcatore della Lazio nella storia del derby (7 reti)?","options":["Silvio Piola","Ciro Immobile","Giorgio Chinaglia","Dejan Stanković"],"answer":0,"cat":"Derby"},
  {"id":118,"q":"Qual è il risultato più largo nella storia del derby (a favore della Roma, 1933)?","options":["5-0","4-0","6-1","5-1"],"answer":0,"cat":"Derby"},
  {"id":119,"q":"Chi è l'allenatore con più panchine della Lazio nei derby?","options":["Simone Inzaghi","Sven-Göran Eriksson","Maurizio Sarri","Zdeněk Zeman"],"answer":0,"cat":"Derby"},
  {"id":120,"q":"Quale giocatore della Lazio detiene il primato di 23 presenze nei derby?","options":["Pino Wilson","Giuseppe Favalli","Stefan Radu","Paolo Negro"],"answer":0,"cat":"Derby"},
  {"id":121,"q":"Chi era il primo gioielliere coinvolto nella morte di Re Cecconi?","options":["Bruno Tabocchini","Giorgio Fraticcioli","Pietro Ghedin","Luigi Martini"],"answer":0,"cat":"Anni 70-90"},
  {"id":122,"q":"Quale compagno di squadra era con Re Cecconi nella gioielleria?","options":["Pietro Ghedin","Luigi Martini","Giancarlo Oddi","Franco Nanni"],"answer":0,"cat":"Anni 70-90"},
  {"id":123,"q":"Quante Supercoppe italiane ha vinto la Lazio (al 2024)?","options":["5","4","3","6"],"answer":0,"cat":"Supercoppe"},
  {"id":124,"q":"In quali anni la Lazio ha vinto la Supercoppa italiana?","options":["1998, 2000, 2009, 2017, 2019","1998, 1999, 2004, 2013, 2019","2000, 2004, 2009, 2013, 2017","1998, 2000, 2013, 2017, 2019"],"answer":0,"cat":"Supercoppe"},
  {"id":125,"q":"Contro chi vinse la Lazio la sua prima Supercoppa italiana nel 1998?","options":["Juventus","Inter","Milan","Parma"],"answer":0,"cat":"Supercoppe"},
  {"id":126,"q":"Quale portiere detiene il record di imbattibilità della Lazio (745 minuti, 1997-98)?","options":["Luca Marchegiani","Angelo Peruzzi","Fernando Orsi","Thomas Strakosha"],"answer":0,"cat":"Numeri"},
  {"id":127,"q":"Quale modulo usava prevalentemente la Lazio di Eriksson nel 1999?","options":["4-4-2 / 4-5-1 fluido","3-5-2","4-3-3 fisso","5-3-2"],"answer":0,"cat":"Tattica"},
  {"id":128,"q":"In quale ruolo Eriksson valorizzò Juan Verón alla Lazio?","options":["Regista arretrato di centrocampo","Trequartista puro","Esterno destro","Seconda punta"],"answer":0,"cat":"Tattica"},
  {"id":129,"q":"Quale presidente ha avuto il mandato più lungo nella storia della Lazio?","options":["Claudio Lotito","Sergio Cragnotti","Umberto Lenzini","Fortunato Ballerini"],"answer":0,"cat":"Storia"},
  {"id":130,"q":"In quale anno Claudio Lotito acquisì il controllo della Lazio?","options":["2004","2002","2006","1998"],"answer":0,"cat":"Storia"},
  {"id":131,"q":"Per il 'caso tamponi' (sentenza definitiva 19 ottobre 2021), a quanto fu ridotta l'inibizione di Lotito?","options":["2 mesi","12 mesi","7 mesi","13 mesi"],"answer":0,"cat":"Storia"},
  {"id":132,"q":"Nel processo d'appello FIGC del 2021 sul 'caso tamponi', a quanto fu portata l'ammenda alla Lazio?","options":["200.000 euro","50.000 euro","150.000 euro","100.000 euro"],"answer":0,"cat":"Storia"},
  {"id":133,"q":"Nel gennaio 2020 Lotito definì lo scudetto 1974 di Lenzini come...","options":["'Nato dal caso'","Il più grande di sempre","Frutto di programmazione","Un trionfo storico"],"answer":0,"cat":"Storia"},
  {"id":134,"q":"Per quale episodio la Lazio fu multata di 50.000 euro dal Tribunale Federale nel gennaio 2018?","options":["Adesivi antisemiti su Anna Frank all'Olimpico","Cori razzisti in trasferta","Illecito amministrativo","Mancato pagamento stipendi"],"answer":0,"cat":"Storia"},
  {"id":135,"q":"Quale scelta di Lotito (luglio 2021) fu condannata dall'Ordine dei Giornalisti del Lazio?","options":["Presentazione di Sarri senza giornalisti presenti","Aumento dei prezzi dei biglietti","Cessione di Milinković","Chiusura della Curva Nord"],"answer":0,"cat":"Storia"},
  {"id":136,"q":"Quale presidente vanta il palmarès più ampio della storia Lazio (7 trofei)?","options":["Sergio Cragnotti","Umberto Lenzini","Claudio Lotito","Gianmarco Calleri"],"answer":0,"cat":"Storia"},
  {"id":137,"q":"Chi era il presidente quando la Lazio vinse la sua prima Coppa Italia (1958)?","options":["Leonardo Siliato","Umberto Lenzini","Fortunato Ballerini","Giorgio Vaccaro"],"answer":0,"cat":"Storia"},
  {"id":138,"q":"Quale ex calciatore-bandiera fu anche presidente della Lazio (1983-1986)?","options":["Giorgio Chinaglia","Pino Wilson","Bruno Giordano","Vincenzo D'Amico"],"answer":0,"cat":"Storia"},
  {"id":139,"q":"In quale stagione la Lazio raggiunse il secondo posto in Serie A con Sarri, tornando in Champions?","options":["2022-23","2020-21","2021-22","2023-24"],"answer":0,"cat":"Moderni"},
  {"id":140,"q":"Quale fu il primo gol della Lazio in una competizione UEFA, segnato da Chinaglia?","options":["Lazio-Sion 3-0 (Coppa UEFA 1973-74)","Lazio-Ipswich","Lazio-Maiorca","Lazio-Porto"],"answer":0,"cat":"Europa"},
];

export const QUIZ_CATEGORIES = [
  "Storia", "Scudetti", "Scudetto 2000", "Coppe Italia", "Europa",
  "Bomber", "Anni 70-90", "Moderni", "Allenatori", "Stadio",
  "Derby", "Numeri", "Mercato", "Tattica", "Supercoppe",
];
